#!/usr/bin/env bash
# setup_linux_toolchain.sh — run ONCE on Linux/WSL to set up the iOS cross-compiler.
#
# No Mac required — downloads the iPhoneOS SDK from xybp888/iOS-SDKs on GitHub.
#
# What this installs:
#   - clang/llvm (arm64-apple-ios cross-compilation)
#   - cctools-port (ld64 Mach-O linker)
#   - ldid (fake codesigning)
#   - iPhoneOS26.5.sdk (from xybp888/iOS-SDKs)
#
# Everything goes to ~/.local/ios-toolchain (no sudo needed after apt)

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
TOOLCHAIN_DIR="$HOME/.local/ios-toolchain"
SDK_VERSION="26.5"
SDK_NAME="iPhoneOS${SDK_VERSION}.sdk"
SDK_URL="https://github.com/xybp888/iOS-SDKs/raw/master/iPhoneOS${SDK_VERSION}.sdk.zip"

RED='\033[0;31m'
GREEN='\033[0;32m'
CYAN='\033[0;36m'
BOLD='\033[1m'
NC='\033[0m'

info()    { echo -e "  ${CYAN}→${NC} $1"; }
success() { echo -e "  ${GREEN}✓${NC} $1"; }
error()   { echo -e "\n  ${RED}✗ Error:${NC} $1\n"; exit 1; }

echo ""
echo -e "${CYAN}${BOLD}  iOS Cross-Compiler Setup${NC}"
echo ""

# ── Install system packages ────────────────────────────────────
info "Installing build dependencies..."
sudo apt-get update -qq
sudo apt-get install -y -qq \
    clang llvm lld \
    git cmake make \
    libssl-dev uuid-dev \
    zip unzip curl \
    python3 \
    2>/dev/null
success "System packages installed"

# ── Create toolchain dir ───────────────────────────────────────
mkdir -p "$TOOLCHAIN_DIR"/{bin,sdk}

# ── Download SDK ───────────────────────────────────────────────
SDK_PATH="$TOOLCHAIN_DIR/sdk/$SDK_NAME"
if [ ! -d "$SDK_PATH" ]; then
    info "Downloading iPhoneOS $SDK_VERSION SDK..."
    TMP_ZIP=$(mktemp /tmp/iPhoneOS.sdk.XXXXXX.zip)
    curl -fsSL --progress-bar "$SDK_URL" -o "$TMP_ZIP" \
        || error "Failed to download SDK from xybp888/iOS-SDKs.\nCheck your internet connection or manually place iPhoneOS.sdk.tar.gz in tools/ and re-run."
    info "Extracting SDK..."
    unzip -q "$TMP_ZIP" -d "$TOOLCHAIN_DIR/sdk/"
    rm -f "$TMP_ZIP"
    [ -d "$SDK_PATH" ] || error "SDK extraction failed — expected $SDK_PATH"
    success "SDK downloaded: $SDK_NAME"
else
    success "SDK already present: $SDK_NAME"
fi

# ── Build cctools-port (ld64 + Apple binutils) ─────────────────
if [ ! -f "$TOOLCHAIN_DIR/bin/arm-apple-darwin-ld" ]; then
    info "Building cctools-port (Apple Mach-O linker)..."
    CCTOOLS_SRC=$(mktemp -d /tmp/cctools.XXXXXX)
    git clone --depth=1 https://github.com/tpoechtrager/cctools-port "$CCTOOLS_SRC" \
        || error "Failed to clone cctools-port"
    cd "$CCTOOLS_SRC/usage_examples/ios_toolchain"
    bash build.sh "$TOOLCHAIN_DIR" "$SDK_PATH" arm 2>&1 | tail -20 \
        || error "cctools-port build failed"
    cd "$SCRIPT_DIR"
    rm -rf "$CCTOOLS_SRC"
    success "cctools-port built"
else
    success "cctools-port: already built"
fi

# ── Build ldid (fake codesigning) ─────────────────────────────
if ! command -v ldid &>/dev/null && [ ! -f "$TOOLCHAIN_DIR/bin/ldid" ]; then
    info "Building ldid..."
    LDID_SRC=$(mktemp -d /tmp/ldid.XXXXXX)
    git clone --depth=1 https://github.com/xerub/ldid "$LDID_SRC" \
        || error "Failed to clone ldid"
    cd "$LDID_SRC"
    make -j$(nproc) 2>&1 | tail -5 || error "ldid build failed"
    cp ldid "$TOOLCHAIN_DIR/bin/ldid"
    cd "$SCRIPT_DIR"
    rm -rf "$LDID_SRC"
    success "ldid built"
else
    success "ldid: found"
fi

# ── Write compiler wrapper scripts ────────────────────────────
info "Writing compiler wrappers..."

cat > "$TOOLCHAIN_DIR/bin/ios-clang" << WRAPPER
#!/bin/sh
exec clang \\
    -target arm64-apple-ios15.0 \\
    -isysroot "$SDK_PATH" \\
    -I"$SDK_PATH/usr/include" \\
    "\$@"
WRAPPER
chmod +x "$TOOLCHAIN_DIR/bin/ios-clang"

cat > "$TOOLCHAIN_DIR/bin/ios-clang++" << WRAPPER
#!/bin/sh
exec clang++ \\
    -target arm64-apple-ios15.0 \\
    -isysroot "$SDK_PATH" \\
    -I"$SDK_PATH/usr/include" \\
    "\$@"
WRAPPER
chmod +x "$TOOLCHAIN_DIR/bin/ios-clang++"

success "Compiler wrappers written"

# ── Write CMake toolchain file ─────────────────────────────────
info "Writing CMake toolchain file..."
cat > "$SCRIPT_DIR/ios-linux-toolchain.cmake" << CMAKE
# iOS cross-compilation toolchain for Linux
# Auto-generated by tools/setup_linux_toolchain.sh

set(CMAKE_SYSTEM_NAME iOS)
set(CMAKE_SYSTEM_PROCESSOR arm64)

set(IOS_TOOLCHAIN_DIR "$TOOLCHAIN_DIR")
set(IOS_SDK_PATH "$SDK_PATH")

set(CMAKE_C_COMPILER   "$TOOLCHAIN_DIR/bin/ios-clang")
set(CMAKE_CXX_COMPILER "$TOOLCHAIN_DIR/bin/ios-clang++")

set(CMAKE_OSX_SYSROOT           "$SDK_PATH")
set(CMAKE_OSX_ARCHITECTURES     arm64)
set(CMAKE_OSX_DEPLOYMENT_TARGET 15.0)

set(CMAKE_FIND_ROOT_PATH "$SDK_PATH")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
CMAKE
success "CMake toolchain file → tools/ios-linux-toolchain.cmake"

# ── Done ───────────────────────────────────────────────────────
echo ""
echo -e "${GREEN}${BOLD}  ✓ Toolchain ready! No Mac required.${NC}"
echo ""
echo "  SDK:       $SDK_PATH"
echo "  Compiler:  $TOOLCHAIN_DIR/bin/ios-clang"
echo ""
echo "  Now run: ./build.sh"
echo ""
